/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antonacube;

/**
 *
 * @author siddh
 */
public class DisplayWindow extends javax.swing.JFrame {

    /**
     * Creates new form DisplayWindow
     */
    public DisplayWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumberOfThreads = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumberOfTests = new javax.swing.JTextField();
        btnExecuteTests = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResults = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rdbNumberOfCores = new javax.swing.JRadioButton();
        rdbCustomNumberOfThreads = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ants on a cube simulation");
        setPreferredSize(new java.awt.Dimension(725, 450));

        jLabel1.setText("Threads at a time:");

        txtNumberOfThreads.setText("4");
        txtNumberOfThreads.setEnabled(false);
        txtNumberOfThreads.setName("lblNumberOfThreads"); // NOI18N

        jLabel2.setText("Numer of tests    :");

        txtNumberOfTests.setText("100");
        txtNumberOfTests.setName("lblNumberOfTests"); // NOI18N

        btnExecuteTests.setText("Execute Tests");
        btnExecuteTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteTestsActionPerformed(evt);
            }
        });

        txtAreaResults.setColumns(20);
        txtAreaResults.setRows(5);
        jScrollPane1.setViewportView(txtAreaResults);

        rdbNumberOfCores.setSelected(true);
        rdbNumberOfCores.setText("Number of Cores");
        rdbNumberOfCores.setName("rdbNumberOfCores"); // NOI18N
        rdbNumberOfCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNumberOfCoresActionPerformed(evt);
            }
        });

        rdbCustomNumberOfThreads.setLabel("Custom");
        rdbCustomNumberOfThreads.setName("rdbCustomNumberOfThreads"); // NOI18N
        rdbCustomNumberOfThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCustomNumberOfThreadsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbNumberOfCores)
                .addGap(26, 26, 26)
                .addComponent(rdbCustomNumberOfThreads)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNumberOfCores)
                    .addComponent(rdbCustomNumberOfThreads))
                .addContainerGap())
        );

        rdbNumberOfCores.getAccessibleContext().setAccessibleName("rdbNumberOfCores");
        rdbCustomNumberOfThreads.getAccessibleContext().setAccessibleName("rdbCustomeNumberOfThreads");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExecuteTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNumberOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtNumberOfThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumberOfThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumberOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExecuteTests)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbNumberOfCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNumberOfCoresActionPerformed
        // TODO add your handling code here:
        if (rdbNumberOfCores.isSelected()) {
            rdbCustomNumberOfThreads.setSelected(false);
            txtNumberOfThreads.setEnabled(false);
        }
    }//GEN-LAST:event_rdbNumberOfCoresActionPerformed

    private void rdbCustomNumberOfThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCustomNumberOfThreadsActionPerformed
        // TODO add your handling code here:
        if (rdbCustomNumberOfThreads.isSelected()) {
            rdbCustomNumberOfThreads.setSelected(true);
            rdbNumberOfCores.setSelected(false);
            txtNumberOfThreads.setEnabled(true);
            
        }
    }//GEN-LAST:event_rdbCustomNumberOfThreadsActionPerformed

    private void btnExecuteTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteTestsActionPerformed
        // TODO add your handling code here:
        int numberOfSimulations = Integer.parseInt(txtNumberOfTests.getText());
        InfoTracker t = null;
        if (rdbNumberOfCores.isSelected()) {
            t = AntOnACube.runSimulations(Runtime.getRuntime().availableProcessors(), numberOfSimulations);
        } else {
            t = AntOnACube.runSimulations(Integer.parseInt(txtNumberOfThreads.getText()), numberOfSimulations);
        }

        if (t == null) {
            //display error message
        } else {
            while (t.getNumberOfCompletedSimulations() != numberOfSimulations) {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ie) {
                    ie.printStackTrace();
                }
            }
            txtAreaResults.setText(t.getEndResult());
        }

    }//GEN-LAST:event_btnExecuteTestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecuteTests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbCustomNumberOfThreads;
    private javax.swing.JRadioButton rdbNumberOfCores;
    private javax.swing.JTextArea txtAreaResults;
    private javax.swing.JTextField txtNumberOfTests;
    private javax.swing.JTextField txtNumberOfThreads;
    // End of variables declaration//GEN-END:variables
}
